version: '3.8'

services:
  web:
    build: ./app
    container_name: suitecrm-web
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb:10.6
    container_name: suitecrm-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  cron:
    build: ./app
    container_name: suitecrm-cron
    volumes:
      - ./app:/var/www/html
    entrypoint: [ "bash", "-c", "cron && tail -f /var/log/cron.log" ]
    depends_on:
      - web
    env_file:
      - .env

volumes:
  db_data:
